In [ ]:
# I. Write a program to create a DataFrame named df from the
# above dictionary data, using labels as the index.


import pandas as pd
import numpy as np
data = {
'creatures': ['Eagles','Eagles','Ducks','Herons','Herons','Eagles','Ducks','Eagles','Herons','Herons','Eagles'],
'weight': [2.0,5,3.0,np.nan,7,2.5,6,np.nan,9,3,2.0],
'frequency': [1,3,2,5,2,3,1,3,4,2,1],
'status': ['no','no','yes',np.nan,'yes','yes','yes','no','yes','yes','no'],
'height': [1.2,2.5,1.8,3.0,2.2,1.9,2.6,1.4,2.8,2.3,1.1],
'region': ['North','South','East','West','North','South','East','West','North','East','South'],
'danger_level': ['low','medium','high','low','high','medium','high','low','medium','high','low']
}

labels = ['x','y','z','w','v','u','t','s','r','q','p']

df = pd.DataFrame(data, index=labels)
print(df)

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

In [ ]:
# II. Write a program to display the basic information of the
# DataFrame, including its summary statistics and data types.

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, x to p
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   creatures     11 non-null     object
 1   weight        9 non-null      float64
 2   frequency     11 non-null     int64
 3   status        10 non-null     object
 4   height        11 non-null     float64
 5   region        11 non-null     object
 6   danger_level  11 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 704.0+ bytes

In [ ]:
df.describe()

         weight  frequency     height
count  9.000000  11.000000  11.000000
mean   4.388889   2.454545   2.072727
std    2.497221   1.293340   0.646670
min    2.000000   1.000000   1.100000
25%    2.500000   1.500000   1.600000
50%    3.000000   2.000000   2.200000
75%    6.000000   3.000000   2.550000
max    9.000000   5.000000   3.000000

In [ ]:
df.dtypes

creatures        object
weight          float64
frequency         int64
status           object
height          float64
region           object
danger_level     object
dtype: object

In [ ]:
# III. Write a program to display every alternate row of the
# DataFrame (starting from index 0).

df.iloc[::2]

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
z     Ducks     3.0          2    yes     1.8   East         high
v    Herons     7.0          2    yes     2.2  North         high
t     Ducks     6.0          1    yes     2.6   East         high
r    Herons     9.0          4    yes     2.8  North       medium
p    Eagles     2.0          1     no     1.1  South          low

In [ ]:

# IV. Write a program to display only rows at index positions 1st,
# 3rd, and 7th from columns creatures and weight of the
# DataFrame.
df.iloc[[1,3,7]][['creatures','weight']]

  creatures  weight
y    Eagles     5.0
w    Herons     NaN
s    Eagles     NaN

In [ ]:
# V. Write a program to select and display the rows where the
# frequency is less than 4.
result = df[df['frequency'] < 4]
print(result)

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

In [ ]:
# VI. Write a program to select and display all rows where there are
# NaN values in the columns weight or status.

result = df[df['weight'].isna() | df['status'].isna()]
print(result)

  creatures  weight  frequency status  height region danger_level
w    Herons     NaN          5    NaN     3.0   West          low
s    Eagles     NaN          3     no     1.4   West          low

In [ ]:
# VII. Write a program to fill the NaN values in the DataFrame with
# the mode (most frequent value) of the respective columns.

df = df.fillna(df.mode().iloc[0])
print(df)

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     2.0          5    yes     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     2.0          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

In [ ]:
# VIII. Write a program to find the total number of frequency visits for
# the bird 'Herons'.

total = df[df['creatures'] == 'Herons']['frequency'].sum()
print("Total frequency visits for Herons:", total)

Total frequency visits for Herons: 13

In [ ]:

# IX.
# Write a program to count and display the number of each type
# of creature in the DataFrame.
count = df['creatures'].value_counts()
print(count)

creatures
Eagles    5
Herons    4
Ducks     2
Name: count, dtype: int64

In [ ]:
# X. Write a program to remove duplicate rows from the DataFrame
# df permanently. Display the DataFrame after the changes.

df.drop_duplicates(inplace=True)
print(df)

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     2.0          5    yes     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     2.0          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

In [ ]:
#xi Write a program to replace the status of 'no' to 'not available'
# for all occurrences in the DataFrame df.

df['status'] = df['status'].replace('no', 'not available')
print(df)

  creatures  weight  frequency         status  height region danger_level
x    Eagles     2.0          1  not available     1.2  North          low
y    Eagles     5.0          3  not available     2.5  South       medium
z     Ducks     3.0          2            yes     1.8   East         high
w    Herons     2.0          5            yes     3.0   West          low
v    Herons     7.0          2            yes     2.2  North         high
u    Eagles     2.5          3            yes     1.9  South       medium
t     Ducks     6.0          1            yes     2.6   East         high
s    Eagles     2.0          3  not available     1.4   West          low
r    Herons     9.0          4            yes     2.8  North       medium
q    Herons     3.0          2            yes     2.3   East         high
p    Eagles     2.0          1  not available     1.1  South          low

In [ ]:
# Write a program to add a new column size to the DataFrame df,
# where the values are based on the height column: label any
# bird taller than 2.5 as 'Large', otherwise label as 'Small'.
df['size'] = df['height'].apply(lambda x: 'Large' if x > 2.5 else 'Small')
print(df)

  creatures  weight  frequency         status  height region danger_level  \
x    Eagles     2.0          1  not available     1.2  North          low
y    Eagles     5.0          3  not available     2.5  South       medium
z     Ducks     3.0          2            yes     1.8   East         high
w    Herons     2.0          5            yes     3.0   West          low
v    Herons     7.0          2            yes     2.2  North         high
u    Eagles     2.5          3            yes     1.9  South       medium
t     Ducks     6.0          1            yes     2.6   East         high
s    Eagles     2.0          3  not available     1.4   West          low
r    Herons     9.0          4            yes     2.8  North       medium
q    Herons     3.0          2            yes     2.3   East         high
p    Eagles     2.0          1  not available     1.1  South          low

    size
x  Small
y  Small
z  Small
w  Large
v  Small
u  Small
t  Large
s  Small
r  Large
q  Small
p  Small

In [ ]:
# Write a program to sort the DataFrame df by danger_level and
# height in descending order.

df_sorted = df.sort_values(by=['danger_level','height'], ascending=False)
print(df_sorted)

  creatures  weight  frequency         status  height region danger_level  \
r    Herons     9.0          4            yes     2.8  North       medium
y    Eagles     5.0          3  not available     2.5  South       medium
u    Eagles     2.5          3            yes     1.9  South       medium
w    Herons     2.0          5            yes     3.0   West          low
s    Eagles     2.0          3  not available     1.4   West          low
x    Eagles     2.0          1  not available     1.2  North          low
p    Eagles     2.0          1  not available     1.1  South          low
t     Ducks     6.0          1            yes     2.6   East         high
q    Herons     3.0          2            yes     2.3   East         high
v    Herons     7.0          2            yes     2.2  North         high
z     Ducks     3.0          2            yes     1.8   East         high

    size
r  Large
y  Small
u  Small
w  Large
s  Small
x  Small
p  Small
t  Large
q  Small
v  Small
z  Small

In [ ]:
# XIV. Write a program to reset the index of the DataFrame df to the
# default integer index, without affecting the original index.

df_reset = df.reset_index()
print(df_reset)

   index creatures  weight  frequency status  height region danger_level
0      x    Eagles     2.0          1     no     1.2  North          low
1      y    Eagles     5.0          3     no     2.5  South       medium
2      z     Ducks     3.0          2    yes     1.8   East         high
3      w    Herons     2.0          5    yes     3.0   West          low
4      v    Herons     7.0          2    yes     2.2  North         high
5      u    Eagles     2.5          3    yes     1.9  South       medium
6      t     Ducks     6.0          1    yes     2.6   East         high
7      s    Eagles     2.0          3     no     1.4   West          low
8      r    Herons     9.0          4    yes     2.8  North       medium
9      q    Herons     3.0          2    yes     2.3   East         high
10     p    Eagles     2.0          1     no     1.1  South          low

In [ ]:
# XV. Write a program to create a new DataFrame df_copy by
# selecting only the rows where weight is greater than 5, and
# include only the columns creatures, weight, and region.

df_copy = df[df['weight'] > 5][['creatures','weight','region']]
print(df_copy)

  creatures  weight region
v    Herons     7.0  North
t     Ducks     6.0   East
r    Herons     9.0  North